version: "3.9"
services:
  yandex.alice.sdk.demo:
    build:
      context: .
      dockerfile: Dockerfile-demo
      args:
        AliceSettings__SkillId: ${ALICESETTINGS_SKILLID}
        AliceSettings__DialogsOAuthToken: ${ALICESETTINGS_DIALOGSOAUTHTOKEN}
    ports:
      - "8000:80"
      - "8001:443"    
    environment:
      - AliceSettings__SkillId=${ALICESETTINGS_SKILLID}
      - AliceSettings__DialogsOAuthToken=${ALICESETTINGS_DIALOGSOAUTHTOKEN}