name: test

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        target: ${{ github.event.pull_request.head.repo.fork && 'unit-test' || 'test' }}
        push: false
        build-args: |
          AliceSettings__SkillId=${{ secrets.SKILL_SKILLID }}
          AliceSettings__DialogsOAuthToken=${{ secrets.DIALOGSAPI_DIALOGSOAUTHTOKEN }}
          AliceSettings__IoTOAuthToken=${{ secrets.ALICESETTINGS_IOTOAUTHTOKEN }}
          AliceSettings__SmartHomeSkillId=${{ secrets.ALICESETTINGS_SMARTHOMESKILLID }}
