name: yandex.alice.sdk

on:
  push:
    branches: 
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './tests/Yandex.Alice.Sdk.Tests/appsettings.json'
      env:
        AliceSettings.SkillId: ${{ secrets.SKILL_SKILLID }}
        AliceSettings.DialogsOAuthToken: ${{ secrets.DIALOGSAPI_DIALOGSOAUTHTOKEN }}
    - name: test
      run: dotnet test ./tests/Yandex.Alice.Sdk.Tests -c Release
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:        
        PROJECT_FILE_PATH: ./src/Yandex.Alice.Sdk/Yandex.Alice.Sdk.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/yandex.alice.sdk.demo:latest
          build-args: |
            AliceSettings__SkillId=${{ secrets.SKILL_SKILLID }}
            AliceSettings__DialogsOAuthToken=${{ secrets.DIALOGSAPI_DIALOGSOAUTHTOKEN }}
