name: yandex.alice.sdk

on:
  push:
    branches: 
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: test
      run: dotnet test ./src -c Release
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:        
        PROJECT_FILE_PATH: ./src/Yandex.Alice.Sdk/Yandex.Alice.Sdk.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
